### ISSUE TITLE
ModuleNotFoundError: No module named 'click'  in the "Perform Initial Training" Section

### ISSUE THREAD

**Issue by Maquinal** [jeffheaton/t81_558_deep_learning#147] opened 2022-07-21 13:07 UTC
![image](https://user-images.githubusercontent.com/109741018/180220394-828788f4-1cd7-4333-89f9-ad295f730691.png)

**Describe the bug**
ModuleNotFoundError: No module named 'click' in the "Perform Initial Training" Section, but also did a pip list and click is installed.

**Expected behavior**
For the code to run without the "No module named 'click' error'

**Which Notebook Contains this Issue**
https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_07_2_train_gan.ipynb

**Comment by jeffheaton** [comment] 2022-07-25 13:27
Probably, colab broke something with an update, I will investigate soon.

**Comment by jeffheaton** [comment] 2022-07-26 17:45
I never did get the error you describe, however, I checked in a fix for another problem introduced by Google CoLab.  Could you try it again and let me know what you get?

https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_07_2_train_gan.ipynb

**Comment by Maquinal** [comment] 2022-07-26 18:47
Hi Jeff, I just realized I left out an important detail so I apologize for that. I am not running in Collab itself, I downloaded the .ipynb file and am running it in a Jupyter Lab environment with a 3090 Cloud GPU.  Maybe it has something to do with that? I will run again with that script and let you know the result. I appreciate the help

**Comment by jeffheaton** [comment] 2022-07-26 21:06
I really can't help there, since I have no access to the environment and have no way to reproduce the issue.

**Closed** 2022-07-26 21:07 UTC
Labels: bug
